openapi: 3.0.3
info:
  title: TH1
  description: TH1
  version: 1.9.0

servers:
  - url: 'http://localhost:{port}/api/v1'
    description: Local server
    variables: {
      port: {
        default: '8080'
      }
    }
  - url: 'http://pg-doener-dev.virt.uni-oldenburg.de:{port}/api/v1'
    description: Dev server
    variables: {
      port: {
        default: '8080'
      }
    }
  - url: 'http://pg-doener-prod.virt.uni-oldenburg.de:{port}/api/v1'
    description: Prod server
    variables: {
      port: {
        default: '8080'
      }
    }

security:
  - BasicAuth: [ ]

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    $ref: './components/schemas/_index.yaml'

paths:
  /table-structures:
    $ref: './paths/table-structure.yaml'

  /table-structures/{id}:
    $ref: './paths/table-structure-id.yaml'

  /converter/{tableStructureId}:
    $ref: './paths/converter-table-structure-id.yaml'

  /converter/preview:
    $ref: './paths/converter-preview.yaml'

  /converter/file:
    $ref: './paths/converter-file.yaml'

  /table-structures/generate:
    $ref: './paths/table-structure-generate.yaml'
