openapi: 3.0.3
info:
  description: TH1
  title: TH1
  version: 1.10.0
servers:
- description: Local server
  url: "http://localhost:{port}/api/v1"
  variables:
    port:
      default: "8080"
- description: Dev server
  url: "http://pg-doener-dev.virt.uni-oldenburg.de:{port}/api/v1"
  variables:
    port:
      default: "8080"
- description: Prod server
  url: "http://pg-doener-prod.virt.uni-oldenburg.de:{port}/api/v1"
  variables:
    port:
      default: "8080"
security:
- BasicAuth: []
paths:
  /table-structures:
    delete:
      operationId: deleteTableStructure
      parameters:
      - in: query
        name: id
        required: true
        schema:
          format: int64
          minimum: 1
          type: integer
      responses:
        "200":
          description: OK
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "404":
          description: Not found
      summary: Delete table structure by id
    get:
      operationId: getTableStructures
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/tableStructureSummary'
                type: array
          description: OK
        "401":
          description: Unauthorized
      summary: Get all table structures
    post:
      operationId: createTableStructure
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/tableStructure'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                format: int64
                minimum: 1
                type: integer
          description: Created
        "400":
          description: Bad request
        "401":
          description: Unauthorized
      summary: Create a new table structure
  /table-structures/{id}:
    get:
      operationId: getTableStructure
      parameters:
      - in: path
        name: id
        required: true
        schema:
          format: int64
          minimum: 1
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tableStructure'
          description: OK
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "404":
          description: Not found
      summary: Get a table structure by id
  /table-structures/generate:
    post:
      operationId: generateTableStructure
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/generateTableStructure_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tableStructure'
          description: OK
        "400":
          description: Bad request
        "401":
          description: Unauthorized
      summary: Generate a tableStructure and return the result as a json
  /converter/{tableStructureId}:
    post:
      operationId: convertTable
      parameters:
      - in: path
        name: tableStructureId
        required: true
        schema:
          format: int64
          minimum: 1
          type: integer
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/generateTableStructure_request'
      responses:
        "200":
          description: OK
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "404":
          description: Not found
      summary: Convert a table and save it to the database
  /converter/preview:
    post:
      operationId: previewConvertTable
      parameters:
      - in: query
        name: limit
        required: false
        schema:
          default: 10
          minimum: 1
          type: integer
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/previewConvertTable_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  items:
                    type: string
                  type: array
                type: array
          description: OK
        "400":
          description: Bad request
        "401":
          description: Unauthorized
      summary: Convert a table and return a preview of the result
  /converter/file:
    post:
      operationId: fileConvertTable
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/previewConvertTable_request'
      responses:
        "200":
          content:
            application/octet-stream:
              schema:
                format: binary
                type: string
          description: OK
        "400":
          description: Bad request
        "401":
          description: Unauthorized
      summary: Convert a table and return the result as a file
  /feedback:
    post:
      operationId: submitFeedback
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/submitFeedback_request'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                format: int64
                minimum: 1
                type: integer
          description: Created
        "400":
          description: Bad request
        "401":
          description: Unauthorized
      summary: Submit feedback
components:
  schemas:
    tableStructure:
      example:
        endColumn: 1
        name: Table structure 1
        structures:
        - name: name
          description: description
          converterType: REMOVE_GROUPED_HEADER
        - name: name
          description: description
          converterType: REMOVE_GROUPED_HEADER
        endRow: 1
        id: 1
      properties:
        id:
          format: int64
          minimum: 1
          type: integer
        name:
          example: Table structure 1
          minLength: 1
          type: string
        structures:
          items:
            $ref: '#/components/schemas/structure'
          minItems: 0
          type: array
        endRow:
          minimum: 1
          type: integer
        endColumn:
          minimum: 1
          type: integer
      required:
      - delimiter
      - name
      - structures
      type: object
    structure:
      discriminator:
        mapping:
          REMOVE_GROUPED_HEADER: '#/components/schemas/removeGroupedHeaderStructure'
          FILL_EMPTY_ROW: '#/components/schemas/fillEmptyRowStructure'
          REMOVE_COLUMN_BY_INDEX: '#/components/schemas/removeColumnByIndexStructure'
          REMOVE_ROW_BY_INDEX: '#/components/schemas/removeRowByIndexStructure'
          ADD_HEADER_NAME: '#/components/schemas/addHeaderNameStructure'
          REMOVE_HEADER: '#/components/schemas/removeHeaderStructure'
          REMOVE_FOOTER: '#/components/schemas/removeFooterStructure'
          REPLACE_ENTRIES: '#/components/schemas/replaceEntriesStructure'
          SPLIT_ROW: '#/components/schemas/splitRowStructure'
          REMOVE_INVALID_ROWS: '#/components/schemas/removeInvalidRowsStructure'
          REMOVE_TRAILING_COLUMN: '#/components/schemas/removeTrailingColumnStructure'
        propertyName: converterType
      example:
        name: name
        description: description
        converterType: REMOVE_GROUPED_HEADER
      oneOf:
      - $ref: '#/components/schemas/removeRowByIndexStructure'
      - $ref: '#/components/schemas/removeColumnByIndexStructure'
      - $ref: '#/components/schemas/removeGroupedHeaderStructure'
      - $ref: '#/components/schemas/fillEmptyRowStructure'
      - $ref: '#/components/schemas/addHeaderNameStructure'
      - $ref: '#/components/schemas/removeHeaderStructure'
      - $ref: '#/components/schemas/removeFooterStructure'
      - $ref: '#/components/schemas/replaceEntriesStructure'
      - $ref: '#/components/schemas/splitRowStructure'
      - $ref: '#/components/schemas/removeInvalidRowsStructure'
      - $ref: '#/components/schemas/removeTrailingColumnStructure'
      properties:
        converterType:
          $ref: '#/components/schemas/converterType'
        name:
          minLength: 1
          type: string
        description:
          minLength: 1
          type: string
      type: object
    tableStructureSummary:
      example:
        name: name
        structures:
        - converterType: REMOVE_GROUPED_HEADER
        - converterType: REMOVE_GROUPED_HEADER
        id: 1
      properties:
        id:
          format: int64
          minimum: 1
          type: integer
        name:
          minLength: 1
          type: string
        structures:
          items:
            $ref: '#/components/schemas/structureSummary'
          minItems: 0
          type: array
      required:
      - id
      - name
      - structures
      type: object
    structureSummary:
      example:
        converterType: REMOVE_GROUPED_HEADER
      properties:
        converterType:
          $ref: '#/components/schemas/converterType'
      required:
      - converterType
      type: object
    converterType:
      enum:
      - REMOVE_GROUPED_HEADER
      - FILL_EMPTY_ROW
      - REMOVE_COLUMN_BY_INDEX
      - REMOVE_ROW_BY_INDEX
      - ADD_HEADER_NAME
      - REMOVE_FOOTER
      - REMOVE_HEADER
      - REPLACE_ENTRIES
      - SPLIT_ROW
      - REMOVE_INVALID_ROWS
      - REMOVE_TRAILING_COLUMN
      type: string
      x-field-extra-annotation: '@de.uol.pgdoener.th1.api.validation.ValidConverterType'
    removeRowByIndexStructure:
      properties:
        converterType:
          $ref: '#/components/schemas/converterType'
        rowIndex:
          items:
            minimum: 0
            type: integer
          minItems: 0
          type: array
      required:
      - converterType
      - rowIndex
      type: object
    removeColumnByIndexStructure:
      properties:
        converterType:
          $ref: '#/components/schemas/converterType'
        columnIndex:
          items:
            minimum: 0
            type: integer
          minItems: 0
          type: array
      required:
      - columnIndex
      - converterType
      type: object
    removeGroupedHeaderStructure:
      properties:
        converterType:
          $ref: '#/components/schemas/converterType'
        rowIndex:
          items:
            minimum: 0
            type: integer
          minItems: 0
          type: array
        columnIndex:
          items:
            minimum: 0
            type: integer
          minItems: 0
          type: array
        startRow:
          minimum: 0
          type: integer
        startColumn:
          minimum: 0
          type: integer
      required:
      - columnIndex
      - converterType
      - rowIndex
      type: object
    addHeaderNameStructure:
      properties:
        converterType:
          $ref: '#/components/schemas/converterType'
        headerNames:
          items:
            minLength: 1
            type: string
          minItems: 0
          type: array
      required:
      - converterType
      - headerNames
      type: object
    fillEmptyRowStructure:
      properties:
        converterType:
          $ref: '#/components/schemas/converterType'
        rowIndex:
          items:
            minimum: 0
            type: integer
          minItems: 0
          type: array
      required:
      - converterType
      - rowIndex
      type: object
    removeHeaderStructure:
      properties:
        converterType:
          $ref: '#/components/schemas/converterType'
        threshold:
          minimum: 0
          type: integer
        blackList:
          items:
            minLength: 0
            type: string
          minItems: 0
          type: array
      required:
      - converterType
      type: object
    removeFooterStructure:
      properties:
        converterType:
          $ref: '#/components/schemas/converterType'
        threshold:
          minimum: 0
          type: integer
        blackList:
          items:
            minLength: 0
            type: string
          minItems: 0
          type: array
      required:
      - converterType
      type: object
    replaceEntriesStructure:
      properties:
        converterType:
          $ref: '#/components/schemas/converterType'
        search:
          minLength: 1
          type: string
        regexSearch:
          minLength: 1
          type: string
        replacement:
          minLength: 0
          type: string
        startRow:
          minimum: 0
          type: integer
        startColumn:
          minimum: 0
          type: integer
        endRow:
          minimum: 0
          type: integer
        endColumn:
          minimum: 0
          type: integer
      required:
      - converterType
      - replacement
      type: object
    splitRowStructure:
      properties:
        converterType:
          $ref: '#/components/schemas/converterType'
        columnIndex:
          minimum: 0
          type: integer
        delimiter:
          minLength: 1
          type: string
        startRow:
          minimum: 0
          type: integer
        endRow:
          minimum: 0
          type: integer
      required:
      - columnIndex
      - converterType
      type: object
    removeInvalidRowsStructure:
      properties:
        converterType:
          $ref: '#/components/schemas/converterType'
        threshold:
          minimum: 0
          type: integer
        blackList:
          items:
            minimum: 0
            type: string
          minItems: 0
          type: array
      required:
      - converterType
      type: object
    removeTrailingColumnStructure:
      properties:
        converterType:
          $ref: '#/components/schemas/converterType'
        threshold:
          minimum: 0
          type: integer
        blackList:
          items:
            minimum: 0
            type: string
          minItems: 0
          type: array
      required:
      - converterType
      type: object
    generateTableStructure_request:
      properties:
        file:
          format: binary
          type: string
      required:
      - file
      type: object
    previewConvertTable_request:
      properties:
        file:
          format: binary
          type: string
        tableStructure:
          $ref: '#/components/schemas/tableStructure'
      required:
      - file
      - tableStructure
      type: object
    submitFeedback_request:
      properties:
        content:
          type: string
      required:
      - content
      type: object
  securitySchemes:
    BasicAuth:
      scheme: basic
      type: http
