name: Validate OpenAPI Document

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: openapitools/openapi-generator-cli:v7.12.0
    steps:
      - uses: actions/checkout@v2
      - name: Validate
        run: validate -i openapi.yaml
